### ISSUE TITLE
Using the command /debug crashes the server 

### ISSUE THREAD

**Issue by ar06x** [agarian-2/MultiOgar#5]
Error:
```
[FATAL] TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type number
    at Function.byteLength (buffer.js:494:11)
at BinaryWriter.writeStringUtf8 (/app/src/packet/BinaryWriter.js:99:25)
at BinaryWriter.writeStringZeroUtf8 (/app/src/packet/BinaryWriter.js:113:10)
at ChatMessage.build (/app/src/packet/ChatMessage.js:48:16)
at WebSocket.sendPacket (/app/src/GameServer.js:1044:29)
at GameServer.sendChatMSG (/app/src/GameServer.js:548:56)
at PlayerCommand.writeLine (/app/src/modules/PlayerCommand.js:14:21)
at PlayerCommand.debug (/app/src/modules/PlayerCommand.js:219:14)
at PlayerCommand.executeCommandLine (/app/src/modules/PlayerCommand.js:22:59)
at GameServer.onChatMSG (/app/src/GameServer.js:521:35)
```

**Comment by ar06x** [comment]
The /pause command also permanently pauses the server

**Comment by agarian-2** [comment]
That's if you use the `pause` command in chat; there's no fix for that. You need to run the command in console to unpause the game.
As for the crash issue, check the commits tab and apply the change I made, as the `Mothercell Nodes` line wasn't meant to be there anyways.
