### ISSUE TITLE
When someone joins server crashes

### ISSUE THREAD

**Issue by urmommy-c** [agarian-2/MultiOgar#7]
[FATAL] TypeError: Cannot read property 'headers' of undefined
    at GameServer.socketEvent (/root/MultiOgar/src/GameServer.js:262:102)
    at WebSocketServer.emit (events.js:315:20)
    at /root/MultiOgar/node_modules/ws/lib/websocket-server.js:90:18
    at WebSocketServer.completeUpgrade (/root/MultiOgar/node_modules/ws/lib/websocket-server.js:329:5)
    at WebSocketServer.handleUpgrade (/root/MultiOgar/node_modules/ws/lib/websocket-server.js:245:10)
    at Server.upgrade (/root/MultiOgar/node_modules/ws/lib/websocket-server.js:89:16)
    at Server.emit (events.js:315:20)
    at onParserExecuteCommon (_http_server.js:646:14)
    at onParserExecute (_http_server.js:587:3)
Any ideas? @agarian-2

**Comment by agarian-2** [comment]
Do not use WS version 3.3.1 as stated in the bot's pull request. Server currently isn't compatible with it. Use 1.1.0 for now until I can figure out what the issue is with 3.3.1.

**Comment by agarian-2** [comment]
Update: For some reason the bot changed the WebSocket version from v3.3.1 to v1.1.5. Since v1.1.5 still works fine, use that version. If necessary, redownload the server and run `npm install` again. Fairly major update to the server has just happened.
